leviking/KikiSaver

init.sql
=> update: created init.sql and database kiki_saver

.gitignore, app.js, package-lock.json, package.json
fixes#7
added necessary package lock, MySQL and Express modules.
Create hello world route at '/'
create mysql connection
added gitignore
=> add node skeleton

app.js
Fixes issue #12 
Fixes issue #13
=> ADD: Add query to check for username and password match in database

app.js
=> add attendance log entry

app.js, init.sql
change ip to string from int
closes #25
=> add ip address to attendance log

public/login.html
closes#33
add ability to log users gps via browser API
=> add ability to register users gps

app.js, init.sql, public/index.html
closes #32 
closes #45  
closes #46
=> update: change gps to string

app.js, public/admin.html
=> Add admin endpoint and admin.html

app.js, init.sql
=> Fix login route

init.sql, public/404.html, public/admin.html, public/index.html, public/login.html, public/signup.html
- 404
- admin
- index
- login
- signup
closes #51 
---------
closes #53 
---------
closes #29
=> update: 1) html to html5 + meta tags, 2) increase string length of username, and 3) add selfie input

public/login.html, public/signup.html
Hi, I added the link to the sign-in page.
=> adde a link to login page on sign-up page

app.js, public/success.html
=> Create success HTML with username and timestamp

app.js
=> Create route redirect at logout to index

public/login.html
=> Added forgot your login.

public/index.html
=> Add logo to homepage

api/db.js, api/login.js, api/sign-up.js, app.js
closes #83 
add dir for api server files
split up server api files
=> add dir for api server files

api/login.js, app.js
=> add event emitter, check for admin flag in db

public/index.html, src/css/style.css
=> centered banner and article one

api/sign-up.js, public/signup.html
=> update: insert first and last name and phone into the db from signup

api/login.js, public/login.html
=> feat: store gps in attendance

api/login.js, app.js
add admin function to protect route, add http headers for auth
work in progress
=> add function to protect admin route,set http head

app.js, public/404.html, public/admin.html, public/index.html, public/login.html, public/signup.html, public/success.html
fixes #107 
remove extraneous routes for '/' and css/js files. add express.static for 'src' directory for smooth static file serving
=> add static for src, update html files

api/login.js, api/sign-up.js, app.js, public/index.html, public/login.html, src/css/style.css
- emit saveselfie function to write selfie_url and make directory
- create a users selfie directory at signup
- install dev dependency nodemon
- add scripts for npm run dev and npm run start
- allow PORT variable from process.env or 3000
- alter sendFile functions to include path
- increase gps length to 80
- clean up header font-size, buttons and center everything
closes #104 
closes #103 
closes #86
=> feat: repair login at save/write selfie to disk and selfie_url

api/login.js, api/sign-up.js, app.js
update port to 3000, edit success on signup response to 200 "oK"
=> change port to 3000, edit signup function

.gitignore, app.js, package-lock.json, package.json, sendgrid.env
=> add email middleware and route

.gitignore, api/attendance.js, api/login.js, api/sign-up.js, app.js
Correct image file extensions now required
=> Fix save selfie file extensions

api/reset.js, app.js, init.sql
Move reset email to reset.js
closes #124 
closes #126
=> Add reset.js - query to DB

api/login.js
pass username & selfie url to react
=> User selfie

api/attendance.js, api/db.js, api/reset.js
update query for resetting user passwords
closes #125
=> update reset query

api/attendance.js, api/db.js, api/fetchUser.js, api/reset.js, app.js
add queries and route to find user id to invalidate magic link
=> Magic query

.gitignore, api/encrypt.js, api/fetchUser.js, api/login.js, api/sign-up.js, package-lock.json, package.json, sendgrid.env
=> add encrypt function

api/changePassword.js, api/encrypt.js, api/login.js, init.sql
* refactor deprecated response status and body
* decode the old password and encode the new password
* encrypt and compare the old password and new password
* increase the gps length
closes #157 
closes #146 
closes #145 
closes #147
=> feat: change password encryption works

api/changePassword.js, api/encrypt.js, api/reset.js, api/sign-up.js, app.js
=> fix change pw stuff
